### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by cbas** [engineersftw/website#2]
Hey @miccheng how does one set up the app for local development? Total Ruby noob here. :angel:  Would like to make some changes to the HTML/CSS and preview on my own machine before doing blind PRs and wasting your time. :wink:

**Comment by miccheng** [comment]
@cbas Oops... yeah, i will need to update the README file. Let me work on that this weekend. Will need it for TechLadies anyways.

**Comment by miccheng** [comment]
@cbas I just updated the [README](https://github.com/engineersftw/website/blob/master/README.md) file with more detailed instructions.

Commit: 81d24a4b98e4b233c2458638c806cc5e1658462e

**Comment by miccheng** [comment]
Closing issue unless @cbas has issues with the instructions.
