### ISSUE TITLE
doesn't search the speaker

### ISSUE THREAD

**Issue by kaihendry** [engineersftw/website#28]
e.g. https://engineers.sg/episodes/search?search=aws+julien has no results

I was it expecting the result:
https://engineers.sg/video/advanced-task-scheduling-with-aws-ecs-aws-user-group-singapore--1466

**Comment by miccheng** [comment]
https://engineers.sg/episodes/search?search=julien <-- this works.

**Comment by miccheng** [comment]
Don't have a full text search engine yet. No plans to implement one yet.
