### ISSUE TITLE
Logo overlaps with menu

### ISSUE THREAD

**Issue by gaqzi** [engineersftw/website#3]
When your screen width is between 993px (tablet breakpoint) and 1180px the logo overlaps with the menu.

993px: 
![engineers_sg](https://cloud.githubusercontent.com/assets/18167/12534974/2b33d714-c2ac-11e5-8b3d-7d44e9f744c5.png)

1180px:
![engineers_sg](https://cloud.githubusercontent.com/assets/18167/12534975/407df05a-c2ac-11e5-94ae-783fb5778004.png)

Not sure what would be the best way of solving this. Possibly break the text and image over two lines? Example (which would be oh so much better if I knew how to make the text appear just below the image, but for an example this is good enough I feel :p): 

![engineers_sg](https://cloud.githubusercontent.com/assets/18167/12534990/12deb976-c2ad-11e5-9be3-42c59bddad08.png)

If you think this looks good I can try and have a go at making that happen.

**Comment by miccheng** [comment]
Lol... its a known bug. Hoping to switch that out with a better looking logo.

**Comment by miccheng** [comment]
I have hidden the text in the menu just before it overlaps.

Commit: 52d01cd8d7fa6ac129e02ea8292510f89056a2ff

**Comment by gaqzi** [comment]
:heart: :kissing_heart:
