### ISSUE TITLE
How does /events get the current data?

### ISSUE THREAD

**Issue by sayanee** [engineersftw/website#30]
Referring to https://github.com/engineersftw/website/blob/master/app/services/webuild_events_service.rb#L2

```  
def get_events(event_url='https://webuild.sg/api/v1/events')
```

Does it already take the list of events from the [OpenShift URL](https://github.com/webuildorg/events#tech-events-in-sg)? 

http://api-webuild.7e14.starter-us-west-2.openshiftapps.com/events

cc @miccheng 🙇‍♀️ Thanks 🙏

**Comment by miccheng** [comment]
We are overwriting the URL with the environment variable. This service class is already using the new URL. The content is cached for a while (maybe 30 minutes). So it should eventually reflect the correct events.
