### ISSUE TITLE
Add a new routes /cal to subscribe to the events calendar

### ISSUE THREAD

**Issue by sayanee** [engineersftw/website#31]
A new URL `https://engineers.sg/cal` should take the OpenShift URL `http://api-webuild.7e14.starter-us-west-2.openshiftapps.com/cal` so that this URL can be used to subscribe to a calendar 📆 

cc @miccheng thanks you 🙏

**Comment by miccheng** [comment]
Done.

**Comment by sayanee** [comment]
closed with #34
