### ISSUE TITLE
More information on the video cards

### ISSUE THREAD

**Issue by gaqzi** [engineersftw/website#4]
I was going to Engineers.sg today to find videos from a specific meetup. I knew the talk had been recorded but looking through the listing wasn't the easiest.

There isn't a lot of information about each video given on the cards. What I think would be useful is:

- The meetup the video was recorded at
- The date of recording
  - The date being clickable and you then get to see other videos recorded at that date for this meetup?
- The speaker
- More of the title. 
  It's mostly unnerving to see 2-3 words out of a title and then dots. Looking at my computer I've to hover over each card to figure out what the video is about. And hopefully that'll tell me which meetup it was for as well.

**Comment by miccheng** [comment]
Actually poking around in that card right this moment at HackerspaceSG. Would love to hear your feedback when i push a first draft to staging later today: https://staging.engineers.sg

**Comment by miccheng** [comment]
@gaqzi Just pushed the new video card design to production. Have a look.

**Comment by gaqzi** [comment]
:heart:

**Comment by miccheng** [comment]
Closing this for now.
