### ISSUE TITLE
API Availability

### ISSUE THREAD

**Issue by woojiahao** [engineersftw/website#47]
I was looking at the Slakoth Slack bot source code and noticed it used the `/api/events` endpoint to retrieve information about events in Singapore and I was thinking of making a similar bot but for the platform called Discord. 

So I was wondering if the `/api` endpoints are free to use? Or must we pay to be able to submit requests to it?

Thanks 🙂

**Comment by miccheng** [comment]
The API is currently read-only. If you want to publish events, we only track Meetup.com events tagged `Technology` and `Singapore`.

**Comment by woojiahao** [comment]
I see, I think being read-only is sufficient for the bot. Thank you! 😄
