### ISSUE TITLE
Integrate Stripe Checkout for donations

### ISSUE THREAD

**Issue by thorsten-stripe** [engineersftw/website#55]
> This is a potential good first issue for someone in the community :)

I'd love for someone to integrate [client-only Checkout](https://stripe.com/docs/payments/checkout/client) basically replicating the functionality on https://engineers.sg/support_us ([see code](https://github.com/engineersftw/website/blob/master/app/views/welcome/support_us.html.slim)) with the different tiers which can be modeled with [plans](https://stripe.com/docs/payments/checkout/client-subscription#create-recurring-products) (for recurring donations) and [products/skus](https://stripe.com/docs/payments/checkout/client#create-products) (for one-time donations) and provide feedback about their experience integrating it.

I'm of course happy to provide guidance and support throughout if helpful. You can reach me via Twitter: https://twitter.com/thorwebdev

**Comment by thorsten-stripe** [comment]
Here is a new sample I added that implements both one-time and recurring donation payments: https://stripe-samples.github.io/github-pages-stripe-checkout/. Maybe useful as inspiration.

**Comment by sarupbanskota** [comment]
I'd like to take this up.

**Comment by thorsten-stripe** [comment]
@sarupbanskota awesome, glad to hear that \o/ What is your preferred way of operating, do you want to take a stab and create a PR yourself, or should we meet up and work on it together?

**Comment by sarupbanskota** [comment]
Hey @thorsten-stripe! 

Sorry I was working through the day and only just got a chance to take a stab at this.

I've started a PR that has the core functionality, although I still gotta clean up some kinks — I'll sort it out tomorrow I think.

I think I'm good to work on the PR independently (except maybe I'll need some Rails tips specific to this repo — my Rails is a few years rusty!).

**Comment by sarupbanskota** [comment]
In the meantime, here are some questions:

1. Is there a Stripe account already setup that I need to use? 

I'll need: 
- [ ] Publishable key
- [ ] `plan` and `sku` values for the 4 + 4 payment plans available on the site

2. Do we already know what we want to do for the [success and cancelled scenario](https://github.com/engineersftw/website/pull/67/files#diff-d15bba12292f6b1ada07694e93bb7b67R64-R65)? (Please link me if there's similar existing code I can look at).

**Comment by sarupbanskota** [comment]
Feedback on the process so far:

This repo:

1. The README is inconsistent in offering setup advice for `zsh`
2. > You should use PG::Connection, PG::Result, and PG::Error instead, respectively.


Stripe:

1. I reset my Stripe password, and my password was weak. It went like this: _enter password, and press enter real quick_ 🚀. Stripe helpfully wanted to tell me my password wasn't strong enough,  but it said it while the submit was happening ... and that state was jittery.

2. Given that the `plan` and `sku` value is used in the API requests, they should be highlighted clearer. It's easy to use the Product ID instead. 

One place it's currently available at, is within SKUs section.

![image](https://user-images.githubusercontent.com/3149580/71829793-5a0f9680-30e0-11ea-9015-e61c812f2625.png)

It's not immediately clear that the `sku_<string>` is the sku you're looking for, and also copying it is very difficult — selecting it and releasing finger triggers a modal.

**Comment by thorsten-stripe** [comment]
> In the meantime, here are some questions:
> 
> 1. Is there a Stripe account already setup that I need to use?
> 
> I'll need:
> 
> * [ ]  Publishable key
> * [ ]  `plan` and `sku` values for the 4 + 4 payment plans available on the site
> 
> 1. Do we already know what we want to do for the [success and cancelled scenario](https://github.com/engineersftw/website/pull/67/files#diff-d15bba12292f6b1ada07694e93bb7b67R64-R65)? (Please link me if there's similar existing code I can look at).

1. Yes, I believe @miccheng has these details. @miccheng could you set up the live [skus](https://stripe.com/docs/payments/checkout/client#create-products) and [plans](https://stripe.com/docs/payments/checkout/client-subscription#create-recurring-products) that should be available to donors and share their details? As well as the live publishable key? Alternatively let us know if you want these to be set via env variables so there is a central config place, should the account ever change for example. Otherwise, completely fine hardcoding them :)

2. I think for the cancel scenario we can simply go back to https://engineers.sg/support_us. For the success scenario, would be nice to show a thank you message, but it doesn't look like something like this already exists. @miccheng do you have an idea what to put on a thank you page? Maybe we can have a video with a thank you message? Or a gif or something fun? Wdyt?

3. Thanks so much for your feedback, super valuable! :)

**Comment by thorsten-stripe** [comment]
And how about adding a little donate button on top of the Become a Patreon button? I think that makes it more visible and shows that direct donations are preferred, wdyt?
![image](https://user-images.githubusercontent.com/23213994/71877571-6b9a8200-3164-11ea-8805-97da217df4c6.png)

**Comment by miccheng** [comment]
> Yes, I believe @miccheng has these details. @miccheng could you set up the live skus and plans that should be available to donors and share their details? As well as the live publishable key? Alternatively let us know if you want these to be set via env variables so there is a central config place, should the account ever change for example. Otherwise, completely fine hardcoding them :)

OK. I will setup the publishable key and SKUs later this evening. Thanks @sarupbanskota.

**Comment by sarupbanskota** [comment]
Thanks @miccheng — if it's an unused account, feel absolutely free to add me to Stripe — happy to set it up directly, and you can remove me after.

sbanskota08@gmail.com

If you're going to do it, that's obviously fine with me — less work! ;)

**Comment by miccheng** [comment]
@sarupbanskota Added you as a developer on our Stripe account.

**Comment by miccheng** [comment]
@sarupbanskota @thorsten-stripe I added some SKU in the test data. Is that enough to start with?

**Comment by sarupbanskota** [comment]
Thanks @miccheng! Just pushed an update with updated Stripe deets.

**Comment by valentine** [comment]
@thorsten-stripe what's the flow like for a contributor to cancel their subscription?

**Comment by thorsten-stripe** [comment]
@valentine as it stands today that needs to be done manually vie the Stripe Dashboard. Every donor receives an email receipt which states the support email address that is set on the Stripe account.

**Comment by valentine** [comment]
I just found the new [customer portal](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal) feature! Guess it's worth opening a new issue to integrate it.
